### ISSUE TITLE
能添加1.6版本的tag吗，或者release。ab_logisticscenter

### ISSUE THREAD

**Issue by lrcstars** [ABackerNINI/factorio_mod#1]
暂时不想搞懂如何写mod，只是想让我1.6版本的游戏，用上你的mod

**Comment by ABackerNINI** [comment]
已添加,不过建议你使用v0.17的版本.
v0.17中修复的bug,添加的特性v0.16中都没有的.
具体你可以查看v0.17的changelog.
当然一般使用的话,v0.16也没太大问题.

**Comment by lrcstars** [comment]
感谢，已经在用了，感觉很不错~
